module.exports.orderStatus = {
    CREATED: "CREATED",
    PREPARING: "PREPARING",
    ONDELIVERY: "ON-DELIVERY",
    COMPLETED: "COMPLETED",
    CANCELED: "CANCELED",
    POSTPONEMENT: "POSTPONEMENT"
}